name: Does it build?

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Why are you triggering me?"
        required: false
        default: "Test run"
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - run: npm i

      - run: npm start
